### ISSUE TITLE
Difference in Tx details in Prod and in Barn

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#142]
Tx hash: 
0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4

[Prod shows 4 transactions](https://explorer.cow.fi/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4): 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/cda91f85-7e83-4484-9732-63d756bcc859)

[DEV shows 5 transactions ](https://pr137--explorer.review.gnosisdev.com/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/?tab=orders)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1047c0d0-0119-4e19-ac03-b22a992bbfc0)

BV diagram shows 4 nodes for both diagrams 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8e55615f-d79a-44cd-bd9a-053337ea0172)

**Expected**: number of transactions should be consistent?

**Comment by ramirotw** [comment]
> Tx hash: 0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4
> 
> [Prod shows 4 transactions](https://explorer.cow.fi/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4): ![image.png](https://camo.githubusercontent.com/814cbc0f89682ee4d22a6ca4a2de76e9588156740e8c226fcaf6c5802aac7872/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566353565633937306132653839306563313066373737382f63646139316638352d376538332d343438342d393733322d363364373536626363383539)
> 
> [DEV shows 5 transactions ](https://pr137--explorer.review.gnosisdev.com/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/?tab=orders) ![image.png](https://camo.githubusercontent.com/89a4aac23d864d133e2044e575ba5ca52ede6dbbd7ef89d42a22a867875944bc/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566353565633937306132653839306563313066373737382f31303437633064302d303131392d346531392d616330332d623232613939326262666330)

This is ok:
- Barn returns 1 order: STRONG -> ETH https://barn.api.cow.fi/mainnet/api/v1/transactions/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/orders 
- Prod returns the other 4 orders:
https://api.cow.fi/mainnet/api/v1/transactions/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/orders

The production site explorer.cow.fi is not merging responses yet, so it will only display the 4 orders from the prod env. On the other hand, the [Release v2.9.0](https://github.com/cowprotocol/explorer/pull/137#) is merging responses so it's fine that it shows 5.

BUT, what is actually not ok is the onchain data, which doesn't have the STRONG -> ETH [order](https://pr137--explorer.review.gnosisdev.com/orders/0x4880647d08051b755ef694c509df1a701047fc734736171fe2378d1fad20d68e6729a00e0cdf0562fa1fb246bc56bbeb6dbbc06262a4796a/).

So this is weird:
1. https://barn.api.cow.fi/mainnet/api/v1/transactions/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/orders returns order id [#0x4880647](https://pr137--explorer.review.gnosisdev.com/orders/0x4880647d08051b755ef694c509df1a701047fc734736171fe2378d1fad20d68e6729a00e0cdf0562fa1fb246bc56bbeb6dbbc06262a4796a/) which is incorrect because that order wasn't included in that tx
2. 
https://barn.api.cow.fi/mainnet/api/v1/trades/?orderUid=0x4880647d08051b755ef694c509df1a701047fc734736171fe2378d1fad20d68e6729a00e0cdf0562fa1fb246bc56bbeb6dbbc06262a4796a has the correct tx hash which is [0x4e50b8d115d449b14c92ef57f66db76269d4ab4197c610d4e1810e8cd6eff7bf](https://etherscan.io/tx/0x4e50b8d115d449b14c92ef57f66db76269d4ab4197c610d4e1810e8cd6eff7bf)

It seems that the Barn API added the order [#0x4880647](https://pr137--explorer.review.gnosisdev.com/orders/0x4880647d08051b755ef694c509df1a701047fc734736171fe2378d1fad20d68e6729a00e0cdf0562fa1fb246bc56bbeb6dbbc06262a4796a/) incorrectly to the batch https://etherscan.io/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4

@anxolin @alfetopito @nlordell

**Comment by nlordell** [comment]
This looks like this known issue: https://github.com/cowprotocol/services/issues/89

**Comment by elena-zh** [comment]
Prod and Dev show the same data now for the transaction in the description.
