### ISSUE TITLE
Surplus + Status label improvements

### ISSUE THREAD

**Issue by alongoni** [cowprotocol/explorer#155]
**Description**
(reported by Anxo)
Surplus breaks a bit with small numbers, and also we don’t handle too well partial executions: The state and surplus of this one could be improved.

We can show the surplus, and the status is something like PARTIAL FILLED

**How to Reproduce**
1. Go to https://explorer.cow.fi/tx/0x8bb4f9644bdf19684d66c55133ded17c198e36069a502f903311eb07ed978145?tab=orders
![image](https://user-images.githubusercontent.com/622217/176773983-4d8d62f8-839e-4592-99f4-3e4dc6beb589.png)

**Comment by elena-zh** [comment]
Hey @alfetopito , @anxolin , is it possible to see/get a TxHash/BV diagram for a partially filled order? 
![image](https://user-images.githubusercontent.com/70885163/179727591-f7307a85-27c6-4b19-832f-f8ddb2359906.png)

**Comment by alfetopito** [comment]
It's possible but not currently implemented.
Each fill/trade will have a different tx hash a be part of a different batch.

There is a wireframe design made since the beginning for this which has never been prioritized https://www.figma.com/file/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=0%3A1

![Screen Shot 2022-07-19 at 11 47 29](https://user-images.githubusercontent.com/43217/179732871-6ba71834-1cf5-4a0d-b907-1ac8589486b0.png)

One thing that I can see from what you shared is that the filled bar is working and we should definitely reduce the decimals in the filled % 😆 

Anyway, it's a different issue than this one

**Comment by elena-zh** [comment]
> One thing that I can see from what you shared is that the filled bar is working and we should definitely reduce the decimals in the filled % 😆
> 
> Anyway, it's a different issue than this one

I have created #164 task for this

**Comment by elena-zh** [comment]
I have also created a task #165 for adding a TxHash to a partially filled orders (maybe one day we will prioritize and implement it)
