### ISSUE TITLE
Filled amount contains fee for a Buy order

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#183]
Related to #161

Filled amount contains fee for a Buy order. 

To reproduce: 
Place a Buy  order in Barn and compare it in [Dev ](https://pr161--gpui.review.gnosisdev.com/rinkeby/orders/0x9085f386be69a4c4c1aac78e6261b5e56b59a6a4efc2d001a056e2fec5c6277aff714b8b0e2700303ec912bd40496c3997ceea2b62f50d2d)environment and in [Barn](0x9085f386be69a4c4c1aac78e6261b5e56b59a6a4efc2d001a056e2fec5c6277aff714b8b0e2700303ec912bd40496c3997ceea2b62f50d2d):
 
**AR**: amounts are different, DEV order contains Fee in the amount
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/70c7a1d4-6124-466e-afbc-96108888acb0)

**ER**: Filled amount = Buy amount (without fee)

**Comment by anxolin** [comment]
I think this is a great catch! Will review. We have something related also in production

If you see this:
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/2352112/184411166-0b02baa0-c0ad-4684-b0ff-c4ffeed32707.png">

https://explorer.cow.fi/rinkeby/orders/0x84b1db5bf9ca32afe11fffa30a828f26c32d43572ce313b3b3e37c5c38527a9779063d9173c09887d536924e2f6eadbabac099f562f4e1e8


Here it says that the order would:
- Use at most              `0.010324057876820693 WETH`
- But ended up using `0.010033647122025 WETH`

Then, the surplus should be `0.010324057876820693-0.010033647122025 = 0.000290410754795693`

However the UI shows `0.000036806442242007`

Then, another issue I see in production, is that, when I check the transaction: https://rinkeby.etherscan.io/tx/0xe981bcb14f014532dd32ad3a4fd0ab11637f3a193bdde88775f1b5c66c7c145d
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/2352112/184412155-ff72aa92-5bbd-4450-a844-64492c8c81b4.png">

I can see the transfered amounts don't match either
* The user actually payed `0.010287251434578686 WETH`
* But the UI says                `0.010033647122025 WETH` --> In this case, the difference is just the fee. So we just need to add the fee to this amount.

-----

Regarding the PR https://github.com/cowprotocol/explorer/pull/161 I see my mistake! I added the fee to the wrong side :) 
In my test I didn't notice it because in the buy order i pasted, the result was exactly because of the rounding (i was adding a extremely small WETH amount to the DAI, so the formatting just didn't showed it, and these two looked the same:
- https://pr161--gpui.review.gnosisdev.com/rinkeby/orders/0x84b1db5bf9ca32afe11fffa30a828f26c32d43572ce313b3b3e37c5c38527a9779063d9173c09887d536924e2f6eadbabac099f562f4e1e8
- https://barn.explorer.cow.fi/rinkeby/orders/0x84b1db5bf9ca32afe11fffa30a828f26c32d43572ce313b3b3e37c5c38527a9779063d9173c09887d536924e2f6eadbabac099f562f4e1e8

Fix on its way!
